Repository teknologi-umum/bot, pull requests merged in 2023-11, with the labels that each got.

#206 feat: hackernews
  src/app.js
  src/hackernews.js
  src/services/hackernews/index.js
Labels: enhancement

#208 Fix sleep time calculation in hackernews.js
  src/hackernews.js
Labels: bug

#207 chore: bump dependencies
  .github/workflows/ci.yml
  .github/workflows/pr.yml
  .nvmrc
  CONTRIBUTING.md
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
Labels: dependencies
